name: CI

on:
  pull_request:
    branches:
      - "*"

  push:

jobs:

  helm:
    name: Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: ["v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1", "v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315"]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Lint
        run: |
          docker run --rm --interactive --network host \
              --name ct-lint \
              --volume $PWD:/workdir \
              --workdir /workdir/charts/apisix \
              quay.io/helmpack/chart-testing:v3.4.0 sh -c 'helm dependency update \
               && cd ../.. \
               && helm repo add bitnami https://charts.bitnami.com/bitnami \
               && helm repo add apisix https://charts.apiseven.com \
               && ct lint \
                  --charts charts/apisix \
                  --charts charts/apisix-dashboard \
                  --charts charts/apisix-ingress-controller'

      - name: fix permissions
        run: |
          sudo mkdir -p $HOME/.kube
          sudo chmod -R 777 $HOME/.kube

      - name: Create Kubernetes ${{ matrix.k8s }} cluster
        id: kind
        uses: ./.github/actions/setup-kind
        with:
          version: v0.17.0
          config: test/e2e/kind.yaml
          image: kindest/node:${{ matrix.k8s }}

      - name: Test
        env:
          KIND_CLUSTER_NAME: kind
          SKIP_CLUSTER_CREATION: true
        run: |
          kind get kubeconfig > $HOME/.kube/kind-config-kind
          docker run --rm --interactive --network host \
              --name ct \
              --volume $HOME/.kube/kind-config-kind:/root/.kube/config \
              --volume $PWD:/workdir \
              --workdir /workdir/charts/apisix \
              quay.io/helmpack/chart-testing:v3.4.0 sh -c 'helm dependency update \
               && cd ../.. \
               && helm repo add bitnami https://charts.bitnami.com/bitnami \
               && helm repo add apisix https://charts.apiseven.com \
               && ct install \
                  --charts charts/apisix'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'

      - name: Run helm-docs
        run: |
          GOBIN=$PWD GO111MODULE=on go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.11.0
          ./helm-docs --chart-search-root=${GITHUB_WORKSPACE}/charts
          DIFF=$(git diff ${GITHUB_WORKSPACE}/charts/**/*md)
          if [ ! -z "$DIFF" ]; then
            echo "Please use helm-docs in your clone, of your fork, of the project, and commit a updated README.md for the chart."
          fi
          git diff --exit-code
          rm -f ./helm-docs
